services:
  elredactor:
    build:
      context: .
      target: dev
    environment:
      - UV_LINK_MODE=copy
    volumes:
      - .:/app
      - /app/.venv # Container deps hot reload lock
      - ./content:/content
    ports:
      - "8000:8000"
      - "5678:5678"
    command: >
      uv run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  postgres_red:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  qdrant:
    ports:
      - "${QDRANT_SERVICE_HTTP_PORT:-6333}:6333"
      - "${QDRANT_SERVICE_GRPC_PORT:-6334}:6334"


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_red

volumes:
  pgadmin_data: