"""create api_credentials

Revision ID: 3d5db0b10cd4
Revises: 7f5e313ca78c
Create Date: 2026-07-24 16:25:35.972662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5db0b10cd4'
down_revision: Union[str, Sequence[str], None] = '7f5e313ca78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_credentials_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_credentials'))
    )
    op.create_index(op.f('ix_api_credentials_key'), 'api_credentials', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_credentials_key'), table_name='api_credentials')
    op.drop_table('api_credentials')
    # ### end Alembic commands ###
