"""refresh documents

Revision ID: b97d3f0b91fa
Revises: 262d78d13a7b
Create Date: 2026-07-26 18:56:56.688883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b97d3f0b91fa"
down_revision: Union[str, Sequence[str], None] = "262d78d13a7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("doc_status", sa.String(), nullable=False))
    op.drop_column("documents", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("documents", "doc_status")
    # ### end Alembic commands ###
