"""add_langgraph_thread_id_to_documents

Revision ID: 0a79b968edc0
Revises: b97d3f0b91fa
Create Date: 2026-07-27 08:39:18.316801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a79b968edc0"
down_revision: Union[str, Sequence[str], None] = "b97d3f0b91fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("langgraph_thread_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "langgraph_thread_id")
    # ### end Alembic commands ###
